### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by samdark**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/q5w3Rj).

### CODE REVIEW

**Comment by rob006** [comment]
@samdark Since when Yii CS rules looks like that? Does Yii 3 has different CS rules than Yii 2?

**Comment by rob006** [comment]
Also: https://github.com/yiisoft/mutex/commit/8fb0bfbe1dbaec1f01aa96362c1517549510b054

**Comment by machour** [comment]
and https://github.com/yiisoft/mutex-file/commit/6acc68f1bac3d1a485cff16ffea194c4ff8f7a13 (had to ignore a rule for tests/bootstrap.php)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-core/blob/master/.styleci.yml should be in the repo.

**Pull request merged**
